# Generated by Django 4.1.5 on 2023-02-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre corto'),
        ),
    ]
