# Generated by Django 4.1.5 on 2023-02-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name'], 'verbose_name': 'Departmento', 'verbose_name_plural': 'Departmentos'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'short_name')},
        ),
    ]
